Development/appmenus/config/routes.rb
  Rails.application.routes.draw do
  

  get 'home/index'
  root 'home#index'  
  
  get 'home/cabecera'
  get 'home/listado'
  get 'home/about'
  get 'orders/new'
  get 'home/vision'
  get 'home/mision'
  get 'home/locales'
  get 'home/mapa'
  
  get 'user'  =>'user#listado'
  
get 'historico'  =>'orders#historico'
  
  resources :menu_orders

  resources :menus
  resources :historico 

  resources :user_orders

  resources :orders do 
    resources :plate_orders
  end
resources :plate_orders do
  resources :type_plates

end
 

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :cities do
      resources :restaurants
  end

 resources :typeplates do
  resources :plates
end

end

Development/appmenus/app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  codename   :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class City < ActiveRecord::Base
    has_many :restaurants, dependent: :destroy
    
    validates :name, presence: true
    
end

Development/appmenus/app/models/menu.rb
# == Schema Information
#
# Table name: menus
#
#  id            :integer          not null, primary key
#  date_menu     :datetime
#  date_end      :datetime
#  restaurant_id :integer
#  plate_id      :integer
#  created_at    :datetime
#  updated_at    :datetime
#  price         :integer
#

class Menu < ActiveRecord::Base
    
    belongs_to :restaurant
    
end

Development/appmenus/app/models/menu_order.rb
# == Schema Information
#
# Table name: menu_orders
#
#  id         :integer          not null, primary key
#  menu_id    :integer
#  order_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class MenuOrder < ActiveRecord::Base
end

Development/appmenus/app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  created_at    :datetime
#  update_at     :datetime
#  address       :string(255)
#  phone         :string(255)
#  restaurant_id :integer
#  updated_at    :datetime
#

class Order < ActiveRecord::Base
    
    has_many :plate_orders
    
    
end

Development/appmenus/app/models/plate.rb
# == Schema Information
#
# Table name: plates
#
#  id           :integer          not null, primary key
#  codeplate    :integer
#  nameplate    :string(255)
#  typeplate_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#  price        :integer
#

class Plate < ActiveRecord::Base
  belongs_to :typeplate
  validates :nameplate, presence: true
  
end

Development/appmenus/app/models/plate_order.rb
# == Schema Information
#
# Table name: plate_orders
#
#  id         :integer          not null, primary key
#  plate_id   :integer
#  order_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class PlateOrder < ActiveRecord::Base
    
    belongs_to :order    
    ###attr_accessible :mensaje
    ###attr_accessible :order
    
end

Development/appmenus/app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id          :integer          not null, primary key
#  coderest    :integer
#  namerest    :string(255)
#  adressrest  :string(255)
#  contactrest :string(255)
#  emailrest   :string(255)
#  city_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Restaurant < ActiveRecord::Base
  belongs_to :city
  has_many   :menus
  validates :namerest, presence: true
  validates :adressrest, presence: true
  validates :contactrest, presence: true
  validates :emailrest, presence: true
  
  def display_menus()
    
    return @Menu.all
  
  end
end

Development/appmenus/app/models/type_user.rb
# == Schema Information
#
# Table name: type_users
#
#  id         :integer          not null, primary key
#  codetype   :integer
#  nametype   :string(255)
#  created_at :datetime
#  update_at  :datetime
#  updated_at :datetime
#

class TypeUser < ActiveRecord::Base
end

Development/appmenus/app/models/typeplate.rb
# == Schema Information
#
# Table name: typeplates
#
#  id         :integer          not null, primary key
#  codetype   :integer
#  nametype   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Typeplate < ActiveRecord::Base
    has_many :plates, dependent: :destroy
  validates :nametype, presence: true
  
end

Development/appmenus/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type_user_id           :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Development/appmenus/app/models/user_order.rb
# == Schema Information
#
# Table name: user_orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  order_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class UserOrder < ActiveRecord::Base
end

Development/appmenus/app/controllers/typeplates_controller.rb
class TypeplatesController < ApplicationController
  before_action :set_typeplate, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @typeplates = Typeplate.all
    respond_with(@typeplates)
  end

  def show
    respond_with(@typeplate)
  end

  def new
    @typeplate = Typeplate.new
    respond_with(@typeplate)
  end

  def edit
  end

  def create
    @typeplate = Typeplate.new(typeplate_params)
    @typeplate.save
    respond_with(@typeplate)
  end

  def update
    @typeplate.update(typeplate_params)
    respond_with(@typeplate)
  end

  def destroy
    @typeplate.destroy
    respond_with(@typeplate)
  end

  private
    def set_typeplate
      @typeplate = Typeplate.find(params[:id])
    end

    def typeplate_params
      params.require(:typeplate).permit(:codetype, :nametype)
    end
end

Development/appmenus/app/helpers/application_helper.rb
module ApplicationHelper
end

Development/appmenus/app/helpers/cities_helper.rb
module CitiesHelper
end

Development/appmenus/app/helpers/historico_helper.rb
module HistoricoHelper
end

Development/appmenus/app/helpers/home_helper.rb
module HomeHelper
end

Development/appmenus/app/helpers/menu_orders_helper.rb
module MenuOrdersHelper
end

Development/appmenus/app/helpers/menus_helper.rb
module MenusHelper
end

Development/appmenus/app/helpers/orders_helper.rb
module OrdersHelper
end

Development/appmenus/app/helpers/plates_helper.rb
module PlatesHelper
end

Development/appmenus/app/helpers/type_users_helper.rb
module TypeUsersHelper
end

Development/appmenus/app/helpers/typeplates_helper.rb
module TypeplatesHelper
end

Development/appmenus/app/helpers/user_helper.rb
module UserHelper
end

Development/appmenus/app/views/typeplates/_form.html.erb
<%= form_for(@typeplate) do |f| %>
  <% if @typeplate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@typeplate.errors.count, "error") %> prohibited this typeplate from being saved:</h2>

      <ul>
      <% @typeplate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codetype %><br>
    <%= f.number_field :codetype %>
  </div>
  <div class="field">
    <%= f.label :nametype %><br>
    <%= f.text_field :nametype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Development/appmenus/app/views/typeplates/edit.html.erb
<h1>Editing typeplate</h1>

<%= render 'form' %>

<%= link_to 'Show', @typeplate %> |
<%= link_to 'Back', typeplates_path %>

Development/appmenus/app/views/typeplates/index.html.erb
<h1>Listing typeplates</h1>

<table>
  <thead>
    <tr>
      <th>Codetype</th>
      <th>Nametype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @typeplates.each do |typeplate| %>
      <tr>
        <td><%= typeplate.codetype %></td>
        <td><%= typeplate.nametype %></td>
        <td><%= link_to 'Show', typeplate %></td>
        <td><%= link_to 'Edit', edit_typeplate_path(typeplate) %></td>
        <td><%= link_to 'Destroy', typeplate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Typeplate', new_typeplate_path %>

Development/appmenus/app/views/typeplates/new.html.erb
<h1>New typeplate</h1>

<%= render 'form' %>

<%= link_to 'Back', typeplates_path %>

Development/appmenus/app/views/typeplates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codetype:</strong>
  <%= @typeplate.codetype %>
</p>

<p>
  <strong>Nametype:</strong>
  <%= @typeplate.nametype %>
</p>

<%= link_to 'Edit', edit_typeplate_path(@typeplate) %> |
<%= link_to 'Plates', typeplate_plates_path(@typeplate) %> |
<%= link_to 'Back', typeplates_path %>